[package]
name = "lightning-rapid-gossip-sync"
<<<<<<< HEAD
version = "0.0.117-rc1"
=======
version = "0.0.117"
>>>>>>> origin/impl-ToSocketAddrs-for-Hostname
authors = ["Arik Sosman <git@arik.io>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/lightningdevkit/rust-lightning"
edition = "2018"
description = """
Utility to process gossip routing data from Rapid Gossip Sync Server.
"""

[features]
default = ["std"]
no-std = ["lightning/no-std"]
std = ["lightning/std"]

[dependencies]
<<<<<<< HEAD
lightning = { version = "0.0.117-rc1", path = "../lightning", default-features = false }
=======
lightning = { version = "0.0.117", path = "../lightning", default-features = false }
>>>>>>> origin/impl-ToSocketAddrs-for-Hostname
bitcoin = { version = "0.29.0", default-features = false }

[target.'cfg(ldk_bench)'.dependencies]
criterion = { version = "0.4", optional = true, default-features = false }

[dev-dependencies]
<<<<<<< HEAD
lightning = { version = "0.0.117-rc1", path = "../lightning", features = ["_test_utils"] }
=======
lightning = { version = "0.0.117", path = "../lightning", features = ["_test_utils"] }
>>>>>>> origin/impl-ToSocketAddrs-for-Hostname
