[package]
name = "lightning-net-tokio"
<<<<<<< HEAD
version = "0.0.117-rc1"
=======
version = "0.0.117"
>>>>>>> origin/impl-ToSocketAddrs-for-Hostname
authors = ["Matt Corallo"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/lightningdevkit/rust-lightning/"
description = """
Implementation of the rust-lightning network stack using Tokio.
For Rust-Lightning clients which wish to make direct connections to Lightning P2P nodes, this is a simple alternative to implementing the required network stack, especially for those already using Tokio.
"""
edition = "2018"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bitcoin = "0.29.0"
<<<<<<< HEAD
lightning = { version = "0.0.117-rc1", path = "../lightning" }
=======
lightning = { version = "0.0.117", path = "../lightning" }
>>>>>>> origin/impl-ToSocketAddrs-for-Hostname
tokio = { version = "1.0", features = [ "rt", "sync", "net", "time" ] }

[dev-dependencies]
tokio = { version = "1.14", features = [ "macros", "rt", "rt-multi-thread", "sync", "net", "time" ] }
<<<<<<< HEAD
lightning = { version = "0.0.117-rc1", path = "../lightning", features = ["_test_utils"] }
=======
lightning = { version = "0.0.117", path = "../lightning", features = ["_test_utils"] }
>>>>>>> origin/impl-ToSocketAddrs-for-Hostname
