[package]
name = "lightning-persister"
<<<<<<< HEAD
version = "0.0.117-rc1"
=======
version = "0.0.117"
>>>>>>> origin/impl-ToSocketAddrs-for-Hostname
authors = ["Valentine Wallace", "Matt Corallo"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/lightningdevkit/rust-lightning"
description = """
Utilities for LDK data persistence and retrieval.
"""
edition = "2018"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bitcoin = "0.29.0"
<<<<<<< HEAD
lightning = { version = "0.0.117-rc1", path = "../lightning" }
=======
lightning = { version = "0.0.117", path = "../lightning" }
>>>>>>> origin/impl-ToSocketAddrs-for-Hostname

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.48.0", default-features = false, features = ["Win32_Storage_FileSystem", "Win32_Foundation"] }

[target.'cfg(ldk_bench)'.dependencies]
criterion = { version = "0.4", optional = true, default-features = false }

[dev-dependencies]
<<<<<<< HEAD
lightning = { version = "0.0.117-rc1", path = "../lightning", features = ["_test_utils"] }
=======
lightning = { version = "0.0.117", path = "../lightning", features = ["_test_utils"] }
>>>>>>> origin/impl-ToSocketAddrs-for-Hostname
bitcoin = { version = "0.29.0", default-features = false }
