[package]
name = "lightning-custom-message"
<<<<<<< HEAD
version = "0.0.117-rc1"
=======
version = "0.0.117"
>>>>>>> origin/impl-ToSocketAddrs-for-Hostname
authors = ["Jeffrey Czyz"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/lightningdevkit/rust-lightning"
description = """
Utilities for supporting custom peer-to-peer messages in LDK.
"""
edition = "2021"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bitcoin = "0.29.0"
<<<<<<< HEAD
lightning = { version = "0.0.117-rc1", path = "../lightning" }
=======
lightning = { version = "0.0.117", path = "../lightning" }
>>>>>>> origin/impl-ToSocketAddrs-for-Hostname
